version: '3'

services:

  kopanowatch:
    build: .
    container_name: kopanowatch
    links:
      - kopanoarchive
    volumes:
      - /var/kopanoarchive:/kopanowatch/archive
      - /var/run/docker.sock:/var/run/docker.sock

  kopanoarchive:
    image: nginx:alpine
    container_name: kopanoarchive
    ports:
      - 127.0.0.1:8081:8081
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - /var/kopanoarchive:/usr/share/nginx/html/kopanoarchive:ro